openapi: '3.0.0'

info:
  title: UI Service
  description: >-
    This service provides the API needed for the User Interfaces.
  version: 0.0.1
  
servers:
  - url: localhost:4000
  
paths:
  /openTrips/true:
    get:
      description: >
        This endpoint gives the lsit of open trips.
      tags:
        - user
      responses:
        '200':
          description: Response object.
          
  /acceptedTrips:
    get:
      description: >
        This endpoint gives accepted trips of all the trucks.
      tags:
        - user
      responses:
        '200':
          description: Response object.
  /getBookedTrips/{truckId}:
    get:
      description: >
        This endpoint gives the booked trips of a truck(accepted trips).
      parameters:
        - in: path
          name: truckId   # Note the name is the same as in the path
          required: true
          schema:
            type: string
      tags:
        - user
      responses:
        '200':
          description: Response object.
          
  /getActiveTrip/{truckId}:
    get:
      description: >
        This endpoint gives the active trip of a driver.
      parameters:
        - in: path
          name: truckId   # Note the name is the same as in the path
          required: true
          schema:
            type: string
      tags:
        - user
      responses:
        '200':
          description: Response object.
  /getDriverStatus/{truckId}:
    get:
      description: >
        This endpoint gives the Driver Status.
      parameters:
        - in: path
          name: truckId   # Note the name is the same as in the path
          required: true
          schema:
            type: string
      tags:
        - user
      responses:
        '200':
          description: Response object.              
  /getCompletedTrip/{truckId}/{value}:
    get:
      description: >
        This endpoint gves all copleted trips of a truck.
      parameters:
        - in: path
          name: truckId   # Note the name is the same as in the path
          required: true
          schema:
            type: string
        - in: path
          name: truckId   # Note the name is the same as in the path
          required: true
          schema:
            type: integer    
      tags:
        - user
      responses:
        '200':
          description: Response object.
  /getInvoices/{truckId}:
    get:
      description: >
        This endpoint gives all active invoices of a truck.
      parameters:
        - in: path
          name: truckId   # Note the name is the same as in the path
          required: true
          schema:
            type: string
      tags:
        - user
      responses:
        '200':
          description: Response object.
